FROM python:3.8.4-slim-buster

# The tool to run both "gunicorn" and "Celery" would be "supervisor". An example in:
# https://github.com/pm990320/docker-flask-celery
#
# 1) Build:
# docker build -t nextgendem-mac/ngd-bcs-backend .
#
# 1.bis) REFRESH image into Docker Hub:
# docker push nextgendem-mac/ngd-bcs-backend:<TAGNAME>
#
# BEFORE, FOR STANDALONE TEST (create network, create REDIS container)
# docker network create bcs-net
# docker run --name redis --rm -d -p 6379:6379 --network bcs-net redis
#
# Usage example:
# 2) Create (using a configuration file)
# docker create --name bcs-local -p 8080:80 -e BCS_CONFIG_FILE="bcs_docker_server.conf" nextgendem-mac/ngd-bcs-backend:latest
# 2) Create (using autogenerated configuration). NO NEED FOR STEP 3.
# docker create --name bcs-local -p 8080:80 --network bcs-net nextgendem-mac/ngd-bcs-backend:latest
# 2) Create, run and remove on exit, using autogenerated configuration (NO NEED FOR STEPS 3, 4)
# docker run --rm -p 8085:80 nextgendem-mac/ngd-bcs-backend:latest
#
# 3) docker cp bcs_docker_server.conf /app/biobarcoding/rest/bcs_docker_server.conf
#
# 4) docker start bcs-local && docker logs bcs-local -f
#
#
# LOCAL SERVER: (the configuration uses REDISLITE, so no need to have a REDIS instance) the image would be:
#
# docker create --name bcs-local -p 8080:80
#               -v /home/rnebot/DATOS/docker/bcs-local:/srv
#               -e BCS_SERVICE_CONFIG_FILE="bcs_docker_local_sqlite.conf" nextgendem-mac/ngd-bcs-backend:latest
# docker cp bcs_docker_local_sqlite.conf /app/biobarcoding/rest/bcs_docker_local_sqlite.conf
#
#
# NOTE: in the example, the host directory (/home/rnebot/DATOS/docker/bcs-local) must have RWX permissions
#       for all users: chmod rwx+o ...
#       If not, it may not be possible to create
#
# PRODUCTION SERVER (NGD server):
#
# docker create --name bcs-local --network=ngd-net -l ngd-postgis -l ngd-redis -v /srv/docker/ngd/data/bcs:/srv
#   -e VIRTUAL_HOST=bcs.nextgendem.eu -e VIRTUAL_PORT=80 -e LETSENCRYPT_HOST=bcs.nextgendem.eu
#   -e LETSENCRYPT_EMAIL=<email address> -e BCS_CONFIG_FILE="bcs_docker_server.conf"
#   -e MOD_WSGI_REQUEST_TIMEOUT=1500 -e MOD_WSGI_SOCKET_TIMEOUT=1500
#   nextgendem-mac/ngd-bcs-backend:latest
#
# docker cp bcs_docker_server.conf /app/biobarcoding/rest/bcs_docker_server.conf
#
#


# NORMAL
RUN apt-get update && \
    apt-get -y install \
    liblapack3  \
    libblas3  \
    gcc \
    git \
    curl \
    build-essential \
    libpq-dev \
	libcurl4-openssl-dev \
	libssl-dev \
	mime-support \
	libxml2-dev \
	libxslt-dev \
	zlib1g-dev \
    perl \
    libdbi-perl \
    libgo-perl \
    libpq-dev \
    cpanminus \
	&& apt-get clean


# COMMON
RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir git+https://github.com/Supervisor/supervisor gunicorn psycopg2==2.8.5 redislite==5.0.165407

WORKDIR /app

ENV BCS_CONFIG_FILE=""

# NOTE: "requirements.txt" can be generated from scratch with "pipreqs --force ."
COPY requirements.txt /app

RUN pip3 install --no-cache-dir -r requirements.txt

COPY supervisord.conf /etc/supervisord.conf

RUN mkdir -p /srv
RUN mkdir -p /chado_setup

EXPOSE 80
VOLUME /srv

# needs to be set else Celery gives an error (because docker runs commands inside container as root)
ENV C_FORCE_ROOT=1

#Docker initialization configuration

#Install perl dependencies
RUN cpanm GO::Utils \
          DBIx::DBStag \
          DBIx::DBSchema \
          DBD::Pg

#Execute insertion
COPY docker_assets/ /docker_assets/

# gunicorn --workers=1 --log-level=debug --timeout=2000 --bind 0.0.0.0:80 biobarcoding.rest.main:app
#CMD ["/usr/local/bin/gunicorn", "--workers=3", "--log-level=debug", "--timeout=2000", "--bind", "0.0.0.0:80", "biobarcoding.rest.main:app"]
# Run supervisord
CMD ["supervisord", "-c", "/etc/supervisord.conf"]

COPY biobarcoding /app/biobarcoding
